[test]
coverage = true
coverageDir = "./coverage"
coverageReporter = ["text", "lcov"]

coveragePathIgnorePatterns = [
  ".claude/**",
  ".github/**",
  "packages/client/tests/**",
  "packages/server/tests/**",
  "tests/**",
  'test-setup.js',
]

preload = ["./test-setup.js"]
