[test]
coverage = true
coverageDir = "./coverage"
coverageReporter = ["text", "lcov"]
coverageThreshold = 0.98

coveragePathIgnorePatterns = [
  ".claude/**",
  ".github/**",
  "packages/client/tests/**",
  "packages/server/tests/**",
  "tests/**",
  'test-setup.ts',
]

preload = ["./test-setup.ts"]
