[test]
coverage = true
coverageDir = "./coverage"
coverageReporter = ["text", "lcov"]

coveragePathIgnorePatterns = [
  ".claude/**",
  ".github/**",
  "client/tests/**",
  "server/tests/**",
  'test-setup.js',
]

preload = ["./test-setup.js"]
