name: Build
on: pull_request
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.3
      - name: Install dependencies
        run: bun install --frozen-lockfile
        working-directory: lib
      - name: Test
        run: bun test
        working-directory: lib
