name: Build
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-24.04
    environment: test
    steps:
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ vars.BUN_VERSION }}
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: server/node_modules
          key: node-modules-${{ hashFiles('server/bun.lock') }}
      - name: Install Dependencies
        run: bun install --frozen-lockfile
        working-directory: server
      - name: Test
        run: bun test
