name: Build
on: pull_request
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Install bun
        run: curl -fsSL https://bun.sh/install | bash
      - name: Install dependencies
        run: bun install
      - name: Test
        run: bun test
