name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-24.04

    environment: publish

    env:
      NPM_CONFIG_TOKEN: ${{ secrets.NPM_CONFIG_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ vars.BUN_VERSION }}

      - name: Copy README.md
        run: cp README.md lib/README.md

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: lib/node_modules
          key: node-modules-${{ hashFiles('lib/bun.lock') }}

      - name: Install dependencies
        run: bun install --frozen-lockfile
        working-directory: lib

      - name: Update package.json version
        run: bun version ${{ github.event.release.tag_name }}

      - name: Commit package.json
        run: |
          git config user.name 'Travis J True'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add package.json
          git commit -m "Updated package.json version to ${{ github.event.release.tag_name }}"
          git push origin HEAD:main
        working-directory: lib

      - name: Publish
        run: bun publish --access public
        working-directory: lib
