name: TEST - Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-24.04

    environment: publish

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ vars.BUN_VERSION }}

      - name: Update package.json version
        run: bun version 0.0.0

      - name: Authenticate with GitHub App
        id: app-token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ secrets.GH_APP_ID }}
          application_private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Commit package.json
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git config --global user.name 'automated-publisher[bot]'
          git config --global user.email 'automated-publisher[bot]@users.noreply.github.com'
          git add lib/package.json
          git commit -m "Updated package.json version to 0.0.0"
          git push
