name: TEST - Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-24.04
    environment: publish
    env:
      NPM_CONFIG_TOKEN: ${{ secrets.NPM_CONFIG_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ vars.BUN_VERSION }}

      - name: Copy README.md
        run: cp README.md lib/README.md

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: lib/node_modules
          key: node-modules-${{ hashFiles('lib/bun.lock') }}

      - name: Install dependencies
        run: bun install --frozen-lockfile
        working-directory: lib

      - name: Update package.json version
        run: bun version ${{ github.event.release.tag_name }}

      - name: Authenticate with GitHub App
        id: app-auth
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Commit package.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json
          git commit -m "Updated package.json version to ${{ github.event.release.tag_name }}"
          git push origin HEAD:main
          git push https://x-access-token:${{ steps.app-auth.outputs.token }}@github.com/travistrue2008/sleepy-serv.git main
        working-directory: lib

      - name: Publish
        run: bun publish --access public
        working-directory: lib
